### ISSUE TITLE
Async/Await Support

### ISSUE THREAD

**Issue by awolden** [signalfx/lambda-nodejs#18]
This library doesn't seem to be getting much action. Is this library still supported? It seems that it is missing async/await support. Is there any plan on supporting this new lambda functionality?

Thanks,
-Alex

**Comment by mstumpfx** [comment]
@awolden Hey Alex, yes we're still supporting it. Async/await support is in our plans and queued up for early next year.

**Comment by awolden** [comment]
Thanks for the fast response @mstumpfx! Glad to hear async lambdas are on the roadmap

**Comment by awolden** [comment]
The PR looks awesome! What are the plans for published this code to a new npm version?

**Comment by mstumpfx** [comment]
Hi @awolden thanks for reminding us 😄 
Just published version 0.0.13 for ya.
